package com.monyx.data

import java.nio.charset.StandardCharsets
import java.time.LocalDate
import java.util.UUID

/**
 * Every local write sets pending = 1 and returns to the UI immediately — the
 * user never waits on the network. Nothing here touches HTTP.
 */
class MonyxRepository(private val dao: MonyxDao) {

    // ------------------------------------------------------------------ reads

    fun categories() = dao.categories()
    fun expenseCategories() = dao.categoriesOfKind("expense")
    fun incomeCategories() = dao.categoriesOfKind("income")
    fun accounts() = dao.accounts()
    fun activeAccounts() = dao.activeAccounts()
    fun members() = dao.members()
    fun accountBalances() = dao.accountBalances()

    /**
     * An empty `accountIds` means every account, archived ones included — the
     * filter narrows what is shown, it never quietly drops history.
     */
    fun monthTotals(period: String, accountIds: Set<String> = emptySet()) =
        dao.monthTotals(period, allAccounts(accountIds), accountIds.toList())

    fun spendByCategory(period: String, accountIds: Set<String> = emptySet()) =
        dao.spendByCategory(period, allAccounts(accountIds), accountIds.toList())

    /** Day-by-day income and expense, under the same account filter as the rest
     *  of the overview. Both ends inclusive. */
    fun dailyTotals(fromDay: String, toDay: String, accountIds: Set<String> = emptySet()) =
        dao.dailyTotals(fromDay, toDay, allAccounts(accountIds), accountIds.toList())

    fun budgetUsage(period: String) = dao.budgetUsage(period)

    fun recentTransactions(period: String = "", limit: Int = 8, accountIds: Set<String> = emptySet()) =
        dao.recentTransactions(period, limit, allAccounts(accountIds), accountIds.toList())

    fun rejectedCount() = dao.rejectedCount()
    fun recurringRules() = dao.recurringRules()
    fun syncStateFlow() = dao.syncStateFlow()

    fun transactions(
        query: String = "",
        categoryId: String? = null,
        accountId: String? = null,
        period: String = "",
    ) = dao.transactions(query, categoryId, accountId, period)

    suspend fun transaction(id: String) = dao.transaction(id)

    // ----------------------------------------------------------------- writes

    /**
     * IDs are generated by the client as UUIDv4, so rows can be created offline
     * without collisions.
     */
    private fun newId(): String = UUID.randomUUID().toString()

    suspend fun addTransaction(
        kind: String,
        amountMinor: Long,
        accountId: String,
        categoryId: String?,
        transferAccountId: String? = null,
        note: String? = null,
        occurredAtMs: Long = System.currentTimeMillis(),
        createdBy: String,
    ): String {
        val id = newId()
        dao.upsertTransactions(
            listOf(
                TransactionEntity(
                    id = id,
                    kind = kind,
                    amountMinor = amountMinor,
                    accountId = accountId,
                    transferAccountId = transferAccountId,
                    categoryId = if (kind == "transfer") null else categoryId,
                    note = note?.takeIf { it.isNotBlank() },
                    occurredAt = occurredAtMs,
                    // The client computes the local date.
                    occurredOn = Dates.localDate(occurredAtMs),
                    createdBy = createdBy,
                    createdAt = System.currentTimeMillis(),
                    pending = 1,
                ),
            ),
        )
        return id
    }

    suspend fun updateTransaction(entity: TransactionEntity) {
        dao.upsertTransactions(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    /**
     * Room keeps tombstones too — the never-physically-delete rule is not
     * server-only. A phone that hard-deleted a budget row would resolve
     * carry-forward to a different month than the server does.
     */
    suspend fun deleteTransaction(id: String) {
        val existing = dao.transaction(id) ?: return
        dao.upsertTransactions(listOf(existing.copy(deleted = 1, pending = 1)))
    }

    suspend fun addAccount(name: String, initialBalanceMinor: Long, icon: String?, color: String?) {
        dao.upsertAccounts(
            listOf(
                AccountEntity(
                    id = newId(),
                    name = name,
                    icon = icon,
                    color = color,
                    initialBalanceMinor = initialBalanceMinor,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun updateAccount(entity: AccountEntity) {
        dao.upsertAccounts(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    /**
     * Archiving is an ordinary edit that happens to sync, not a deletion: the
     * row keeps its id, its balance and every transaction pointing at it.
     */
    suspend fun setAccountArchived(entity: AccountEntity, archived: Boolean) {
        dao.upsertAccounts(
            listOf(entity.copy(archived = if (archived) 1 else 0, pending = 1, rejected = 0)),
        )
    }

    suspend fun deleteAccount(entity: AccountEntity) {
        dao.upsertAccounts(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    suspend fun addCategory(
        name: String,
        kind: String,
        parentId: String?,
        icon: String?,
        color: String?,
    ) {
        dao.upsertCategories(
            listOf(
                CategoryEntity(
                    id = newId(),
                    parentId = parentId,
                    name = name,
                    icon = icon,
                    color = color,
                    kind = kind,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun updateCategory(entity: CategoryEntity) {
        dao.upsertCategories(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    suspend fun deleteCategory(entity: CategoryEntity) {
        dao.upsertCategories(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    /**
     * Editing a limit for a month inserts a row for that month; every later
     * month inherits it.
     *
     * The id is derived from (categoryId, period) rather than random. The server
     * carries UNIQUE (household_id, category_id, period), so two devices that
     * each created a budget for the same category and month offline would
     * otherwise arrive with two different ids and collide on that constraint.
     * A derived id makes the two pushes the same upsert instead of a conflict.
     * See docs/decisions/0002-budget-ids-are-derived.md.
     */
    private fun budgetId(categoryId: String, period: String): String =
        UUID.nameUUIDFromBytes("budget:$categoryId:$period".toByteArray(StandardCharsets.UTF_8))
            .toString()

    /**
     * Derived for the same reason budget ids are, and it matters more here:
     * month_plans is UNIQUE on (household, period) with no category to
     * distinguish rows, so two phones planning August offline collide on
     * literally every field but the id. Deriving it makes them one upsert.
     */
    private fun monthPlanId(period: String): String =
        UUID.nameUUIDFromBytes("month_plan:$period".toByteArray(StandardCharsets.UTF_8))
            .toString()

    fun monthPlan(period: String) = dao.monthPlan(period)

    suspend fun setMonthPlan(period: String, plannedMinor: Long) {
        dao.upsertMonthPlans(
            listOf(
                MonthPlanEntity(
                    id = monthPlanId(period),
                    period = period,
                    plannedMinor = plannedMinor,
                    deleted = 0,
                    pending = 1,
                ),
            ),
        )
    }

    /**
     * What to put in the field when a month has no plan yet: the last plan made,
     * else what actually came in last month. Both beat a blank field — planning
     * a month is nearly always last month with a nudge.
     */
    suspend fun suggestedPlanMinor(period: String): Long =
        dao.previousPlannedMinor(period)
            ?: dao.incomeMinorIn(Dates.shiftPeriod(period, -1))

    suspend fun setBudget(categoryId: String, period: String, limitMinor: Long) {
        dao.upsertBudgets(
            listOf(
                BudgetEntity(
                    id = budgetId(categoryId, period),
                    categoryId = categoryId,
                    period = period,
                    limitMinor = limitMinor,
                    deleted = 0,
                    pending = 1,
                ),
            ),
        )
    }

    /**
     * Removing a limit is a tombstone for that period, and inheritance stops
     * there — a deleted row is still the newest row, it just carries no limit.
     */
    suspend fun clearBudget(categoryId: String, period: String) {
        dao.upsertBudgets(
            listOf(
                BudgetEntity(
                    id = budgetId(categoryId, period),
                    categoryId = categoryId,
                    period = period,
                    limitMinor = 0,
                    deleted = 1,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun effectiveBudget(categoryId: String, period: String) =
        dao.effectiveBudget(categoryId, period)

    // ------------------------------------------------------- recurring rules

    suspend fun addRecurringRule(
        kind: String,
        amountMinor: Long,
        accountId: String,
        categoryId: String?,
        note: String?,
        freq: String,
        startsOn: LocalDate,
        endsOn: LocalDate?,
        createdBy: String,
    ): String {
        val id = newId()
        dao.upsertRecurringRules(
            listOf(
                RecurringRuleEntity(
                    id = id,
                    kind = kind,
                    amountMinor = amountMinor,
                    accountId = accountId,
                    categoryId = categoryId,
                    note = note?.takeIf { it.isNotBlank() },
                    freq = freq,
                    startsOn = startsOn.toString(),
                    endsOn = endsOn?.toString(),
                    createdBy = createdBy,
                    createdAt = System.currentTimeMillis(),
                    pending = 1,
                ),
            ),
        )
        return id
    }

    suspend fun updateRecurringRule(entity: RecurringRuleEntity) {
        dao.upsertRecurringRules(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    suspend fun recurringRule(id: String) = dao.recurringRule(id)

    /**
     * Stopping a rule is a tombstone, and it stops the rule ONLY. Every
     * transaction it already produced stays exactly where it is: money that has
     * been spent does not un-spend because the household cancelled the
     * subscription.
     */
    suspend fun deleteRecurringRule(entity: RecurringRuleEntity) {
        dao.upsertRecurringRules(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    /**
     * Write the transactions every rule owes up to [today], and return how many
     * were created.
     *
     * Idempotent by construction rather than by bookkeeping. Each occurrence has
     * an id derived from (rule, date), so this asks the database which of those
     * ids it already holds and writes only the rest — no cursor column to keep
     * in step, and nothing to go wrong when two phones run it at once.
     *
     * Called from two places, and the difference matters. SyncWorker runs it
     * AFTER the pull — both orders converge, but pulling first means a tombstone
     * for an occurrence someone else deleted has already arrived, so it is never
     * briefly rewritten and re-pushed. App open runs it with no sync at all,
     * which is the only path that works offline.
     */
    suspend fun materializeRecurring(today: LocalDate = Dates.today()): Int {
        var written = 0
        for (rule in dao.activeRecurringRules()) {
            val anchor = parseDate(rule.startsOn) ?: continue
            val dates = Recurrence.occurrences(
                freq = rule.freq,
                anchor = anchor,
                endsOn = rule.endsOn?.let(::parseDate),
                through = today,
            )
            if (dates.isEmpty()) continue

            val ids = dates.map { Recurrence.occurrenceId(rule.id, it) }
            // Chunked because Room expands `IN (:ids)` to one bind variable per
            // id, and SQLite's limit is 999 on older Android builds.
            val known = ids.chunked(500).flatMap { dao.existingTransactionIds(it) }.toSet()

            val fresh = dates.asSequence()
                .map { it to Recurrence.occurrenceId(rule.id, it) }
                .filterNot { it.second in known }
                .take(MAX_NEW_PER_PASS)
                .toList()
            if (fresh.isEmpty()) continue

            dao.upsertTransactions(
                fresh.map { (date, id) ->
                    val at = Recurrence.occurredAt(date)
                    TransactionEntity(
                        id = id,
                        kind = rule.kind,
                        amountMinor = rule.amountMinor,
                        accountId = rule.accountId,
                        categoryId = rule.categoryId,
                        note = rule.note,
                        occurredAt = at,
                        occurredOn = date.toString(),
                        // The rule's author, not whoever's phone happened to run
                        // this: every field has to be a pure function of
                        // (rule, date) or two phones overwrite each other.
                        createdBy = rule.createdBy,
                        recurringRuleId = rule.id,
                        createdAt = at,
                        pending = 1,
                    )
                },
            )
            written += fresh.size
        }
        return written
    }

    private fun parseDate(value: String): LocalDate? =
        runCatching { LocalDate.parse(value) }.getOrNull()

    /**
     * Step 3 of the restore runbook. Without this, the copies of the data
     * sitting on four phones cannot be used to repair the server.
     */
    suspend fun reuploadEverything() {
        dao.markAllAccountsPending()
        dao.markAllCategoriesPending()
        dao.markAllBudgetsPending()
        dao.markAllMonthPlansPending()
        dao.markAllRecurringRulesPending()
        dao.markAllTransactionsPending()
    }

    companion object {
        /**
         * How many transactions one rule may create in a single pass.
         *
         * A limit on damage, not on the schedule. A rule whose anchor year was
         * mistyped, or a phone whose clock is wrong, would otherwise fill the
         * history in one go. Occurrences are taken oldest first, so a rule with
         * a genuine backlog still drains it — a pass at a time, visibly, instead
         * of in one silent flood.
         */
        internal const val MAX_NEW_PER_PASS = 60

        /**
         * On the companion so a test can pin the direction without a database.
         * Inverting this is the one mistake here that fails silently and
         * completely: every overview figure would read zero, with no error and
         * no empty state to explain it.
         */
        internal fun allAccounts(ids: Set<String>): Int = if (ids.isEmpty()) 1 else 0
    }
}
