package com.monyx.data

import java.nio.charset.StandardCharsets
import java.time.LocalDate
import java.util.UUID

/**
 * Every local write sets pending = 1 and returns to the UI immediately — the
 * user never waits on the network. Nothing here touches HTTP.
 */
class MonyxRepository(private val dao: MonyxDao) {

    // ------------------------------------------------------------------ reads

    fun categories() = dao.categories()
    fun expenseCategories() = dao.categoriesOfKind("expense")
    fun incomeCategories() = dao.categoriesOfKind("income")
    fun accounts() = dao.accounts()
    fun activeAccounts() = dao.activeAccounts()
    fun members() = dao.members()
    fun accountBalances() = dao.accountBalances()

    /** Balances as they stood at the end of [through] (an ISO local date). */
    fun accountBalancesThrough(through: String) = dao.accountBalancesThrough(through)
    fun spendingAccountIds(period: String) = dao.spendingAccountIds(period)

    /** Every top-level spending category, spent on or not — the charts pad with these. */
    fun rootExpenseCategories() = dao.rootExpenseCategories()

    /**
     * An empty `accountIds` means every account, archived ones included — the
     * filter narrows what is shown, it never quietly drops history.
     */
    fun monthTotals(period: String, accountIds: Set<String> = emptySet()) =
        dao.monthTotals(period, allAccounts(accountIds), accountIds.toList())

    fun spendByCategory(period: String, accountIds: Set<String> = emptySet()) =
        dao.spendByCategory(period, allAccounts(accountIds), accountIds.toList())

    /** The breakdown month by month, both ends inclusive, under the same account
     *  filter as the month the pie chart shows. */
    fun spendByCategoryPerMonth(
        fromPeriod: String,
        toPeriod: String,
        accountIds: Set<String> = emptySet(),
    ) = dao.spendByCategoryPerMonth(fromPeriod, toPeriod, allAccounts(accountIds), accountIds.toList())

    /** Day-by-day income and expense, under the same account filter as the rest
     *  of the overview. Both ends inclusive. */
    fun dailyTotals(fromDay: String, toDay: String, accountIds: Set<String> = emptySet()) =
        dao.dailyTotals(fromDay, toDay, allAccounts(accountIds), accountIds.toList())

    /** How far the selected accounts' balance moved each day — transfers and all. */
    fun dailyDeltas(fromDay: String, toDay: String, accountIds: Set<String> = emptySet()) =
        dao.dailyDeltas(fromDay, toDay, allAccounts(accountIds), accountIds.toList())

    fun budgetUsage(period: String) = dao.budgetUsage(period)

    /** Raw budget rows for the history chart's limit line. No account filter:
     *  a limit belongs to the household, not to an account. */
    fun budgetLimitsThrough(toPeriod: String) = dao.budgetLimitsThrough(toPeriod)

    fun recentTransactions(period: String = "", limit: Int = 8, accountIds: Set<String> = emptySet()) =
        dao.recentTransactions(period, limit, allAccounts(accountIds), accountIds.toList())

    fun rejectedCount() = dao.rejectedCount()
    fun recurringRules() = dao.recurringRules()
    fun syncStateFlow() = dao.syncStateFlow()

    fun transactions(
        query: String = "",
        categoryId: String? = null,
        accountId: String? = null,
        period: String = "",
    ) = dao.transactions(query, categoryId, accountId, period)

    suspend fun transaction(id: String) = dao.transaction(id)

    // ----------------------------------------------------------------- writes

    /**
     * IDs are generated by the client as UUIDv4, so rows can be created offline
     * without collisions.
     */
    private fun newId(): String = UUID.randomUUID().toString()

    suspend fun addTransaction(
        kind: String,
        amountMinor: Long,
        accountId: String,
        categoryId: String?,
        transferAccountId: String? = null,
        note: String? = null,
        occurredAtMs: Long = System.currentTimeMillis(),
        createdBy: String,
        /**
         * How the row got here. The column and its CHECK constraint have
         * allowed 'voice' since the first migration and Mapping.kt already
         * round-trips it, so marking a dictated row costs no schema change —
         * and without the marker there is no way to ever measure how often the
         * parser was right.
         */
        source: String = "manual",
    ): String {
        val id = newId()
        dao.upsertTransactions(
            listOf(
                TransactionEntity(
                    id = id,
                    kind = kind,
                    amountMinor = amountMinor,
                    accountId = accountId,
                    transferAccountId = transferAccountId,
                    categoryId = if (kind == "transfer") null else categoryId,
                    note = note?.takeIf { it.isNotBlank() },
                    occurredAt = occurredAtMs,
                    // The client computes the local date.
                    occurredOn = Dates.localDate(occurredAtMs),
                    createdBy = createdBy,
                    source = source,
                    createdAt = System.currentTimeMillis(),
                    pending = 1,
                ),
            ),
        )
        return id
    }

    suspend fun updateTransaction(entity: TransactionEntity) {
        dao.upsertTransactions(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    /**
     * Room keeps tombstones too — the never-physically-delete rule is not
     * server-only. A phone that hard-deleted a budget row would resolve
     * carry-forward to a different month than the server does.
     */
    suspend fun deleteTransaction(id: String) {
        val existing = dao.transaction(id) ?: return
        // rejected = 0 with it. A row the server refused and the household then
        // deleted is not a rejected row any more, and leaving the flag set
        // leaves it counted in rejectedCount() for as long as the phone lives.
        dao.upsertTransactions(listOf(existing.copy(deleted = 1, pending = 1, rejected = 0)))
    }

    suspend fun addAccount(name: String, initialBalanceMinor: Long, icon: String?, color: String?) {
        dao.upsertAccounts(
            listOf(
                AccountEntity(
                    id = newId(),
                    name = name,
                    icon = icon,
                    color = color,
                    initialBalanceMinor = initialBalanceMinor,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun updateAccount(entity: AccountEntity) {
        dao.upsertAccounts(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    /**
     * Writes the order the user dragged the accounts into.
     *
     * Position, not rank: sortOrder becomes the index, so there are no gaps to
     * run out of and no renumbering pass to schedule later. Every row is
     * rewritten because a single move shifts every position after it anyway,
     * and the whole list is a handful of rows.
     *
     * `pending = 1` on all of them: order is shared household state, the same
     * as a name or a colour, and a phone that reorders offline has to carry
     * that to everyone else.
     */
    suspend fun reorderAccounts(ordered: List<AccountEntity>) {
        dao.upsertAccounts(
            ordered.mapIndexed { index, entity ->
                entity.copy(sortOrder = index, pending = 1, rejected = 0)
            },
        )
    }

    /**
     * Archiving is an ordinary edit that happens to sync, not a deletion: the
     * row keeps its id, its balance and every transaction pointing at it.
     */
    suspend fun setAccountArchived(entity: AccountEntity, archived: Boolean) {
        dao.upsertAccounts(
            listOf(entity.copy(archived = if (archived) 1 else 0, pending = 1, rejected = 0)),
        )
    }

    suspend fun deleteAccount(entity: AccountEntity) {
        dao.upsertAccounts(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    suspend fun addCategory(
        name: String,
        kind: String,
        parentId: String?,
        icon: String?,
        color: String?,
    ) {
        dao.upsertCategories(
            listOf(
                CategoryEntity(
                    id = newId(),
                    parentId = parentId,
                    name = name,
                    icon = icon,
                    color = color,
                    kind = kind,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun updateCategory(entity: CategoryEntity) {
        dao.upsertCategories(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    /**
     * Writes the order of ONE list of siblings — the roots of a kind, or the
     * children of a single parent. See [reorderAccounts].
     *
     * Siblings only, because dragging a category out of its family would be a
     * reparent, and nesting is exactly one level deep by construction. The
     * numbering restarts per list, which is why every read path orders by
     * `sortOrder, name` and groups before it sorts.
     */
    suspend fun reorderCategories(ordered: List<CategoryEntity>) {
        dao.upsertCategories(
            ordered.mapIndexed { index, entity ->
                entity.copy(sortOrder = index, pending = 1, rejected = 0)
            },
        )
    }

    suspend fun deleteCategory(entity: CategoryEntity) {
        dao.upsertCategories(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    /**
     * Editing a limit for a month inserts a row for that month; every later
     * month inherits it.
     *
     * The id is derived from (categoryId, period) rather than random. The server
     * carries UNIQUE (household_id, category_id, period), so two devices that
     * each created a budget for the same category and month offline would
     * otherwise arrive with two different ids and collide on that constraint.
     * A derived id makes the two pushes the same upsert instead of a conflict.
     * See docs/decisions/0002-budget-ids-are-derived.md.
     */
    private fun budgetId(categoryId: String, period: String): String =
        UUID.nameUUIDFromBytes("budget:$categoryId:$period".toByteArray(StandardCharsets.UTF_8))
            .toString()

    /**
     * Derived for the same reason budget ids are, and it matters more here:
     * month_plans is UNIQUE on (household, period) with no category to
     * distinguish rows, so two phones planning August offline collide on
     * literally every field but the id. Deriving it makes them one upsert.
     */
    private fun monthPlanId(period: String): String =
        UUID.nameUUIDFromBytes("month_plan:$period".toByteArray(StandardCharsets.UTF_8))
            .toString()

    fun monthPlan(period: String) = dao.monthPlan(period)

    suspend fun setMonthPlan(period: String, plannedMinor: Long) {
        dao.upsertMonthPlans(
            listOf(
                MonthPlanEntity(
                    id = monthPlanId(period),
                    period = period,
                    plannedMinor = plannedMinor,
                    deleted = 0,
                    pending = 1,
                ),
            ),
        )
    }

    /**
     * What to put in the field when a month has no plan yet: the last plan made,
     * else what actually came in last month. Both beat a blank field — planning
     * a month is nearly always last month with a nudge.
     */
    suspend fun suggestedPlanMinor(period: String): Long =
        dao.previousPlannedMinor(period)
            ?: dao.incomeMinorIn(Dates.shiftPeriod(period, -1))

    suspend fun setBudget(categoryId: String, period: String, limitMinor: Long) {
        dao.upsertBudgets(
            listOf(
                BudgetEntity(
                    id = budgetId(categoryId, period),
                    categoryId = categoryId,
                    period = period,
                    limitMinor = limitMinor,
                    deleted = 0,
                    pending = 1,
                ),
            ),
        )
    }

    /**
     * Removing a limit is a tombstone for that period, and inheritance stops
     * there — a deleted row is still the newest row, it just carries no limit.
     */
    suspend fun clearBudget(categoryId: String, period: String) {
        dao.upsertBudgets(
            listOf(
                BudgetEntity(
                    id = budgetId(categoryId, period),
                    categoryId = categoryId,
                    period = period,
                    limitMinor = 0,
                    deleted = 1,
                    pending = 1,
                ),
            ),
        )
    }

    suspend fun effectiveBudget(categoryId: String, period: String) =
        dao.effectiveBudget(categoryId, period)

    // ------------------------------------------------------- recurring rules

    suspend fun addRecurringRule(
        kind: String,
        amountMinor: Long,
        accountId: String,
        categoryId: String?,
        note: String?,
        freq: String,
        startsOn: LocalDate,
        endsOn: LocalDate?,
        createdBy: String,
    ): String {
        val id = newId()
        dao.upsertRecurringRules(
            listOf(
                RecurringRuleEntity(
                    id = id,
                    kind = kind,
                    amountMinor = amountMinor,
                    accountId = accountId,
                    categoryId = categoryId,
                    note = note?.takeIf { it.isNotBlank() },
                    freq = freq,
                    startsOn = startsOn.toString(),
                    endsOn = endsOn?.toString(),
                    createdBy = createdBy,
                    createdAt = System.currentTimeMillis(),
                    pending = 1,
                ),
            ),
        )
        return id
    }

    /**
     * Writes the order the rules were dragged into. Position, not rank, exactly
     * as [reorderAccounts] and [reorderCategories] do it: sortOrder becomes the
     * index, so there are no gaps to run out of and no renumbering pass later.
     *
     * The whole list every time, because a drag moves one row and shifts every
     * row between its old and new place — writing only the dragged one would
     * leave two rules claiming the same position.
     *
     * Ids rather than entities, unlike its two siblings: the settings list is
     * built from a join projection and does not hold the rows. Reading them back
     * here is a handful of primary-key lookups and keeps the screen from
     * carrying a second copy of every rule purely so it can hand it back.
     */
    suspend fun reorderRecurringRules(orderedIds: List<String>) {
        val rows = orderedIds.mapIndexedNotNull { index, id ->
            dao.recurringRule(id)?.copy(sortOrder = index, pending = 1, rejected = 0)
        }
        if (rows.isNotEmpty()) dao.upsertRecurringRules(rows)
    }

    suspend fun updateRecurringRule(entity: RecurringRuleEntity) {
        dao.upsertRecurringRules(listOf(entity.copy(pending = 1, rejected = 0)))
    }

    suspend fun recurringRule(id: String) = dao.recurringRule(id)

    /**
     * Stopping a rule is a tombstone, and it stops the rule ONLY. Every
     * transaction it already produced stays exactly where it is: money that has
     * been spent does not un-spend because the household cancelled the
     * subscription.
     */
    suspend fun deleteRecurringRule(entity: RecurringRuleEntity) {
        dao.upsertRecurringRules(listOf(entity.copy(deleted = 1, pending = 1)))
    }

    /**
     * Write the transactions every rule owes up to [today], and return how many
     * were created.
     *
     * Idempotent by construction rather than by bookkeeping. Each occurrence has
     * an id derived from (rule, date), so this asks the database which of those
     * ids it already holds and writes only the rest — no cursor column to keep
     * in step, and nothing to go wrong when two phones run it at once.
     *
     * Called from two places, and the difference matters. SyncWorker runs it
     * AFTER the pull — both orders converge, but pulling first means a tombstone
     * for an occurrence someone else deleted has already arrived, so it is never
     * briefly rewritten and re-pushed. App open runs it with no sync at all,
     * which is the only path that works offline.
     */
    suspend fun materializeRecurring(today: LocalDate = Dates.today()): Int {
        var written = 0
        for (rule in dao.activeRecurringRules()) {
            val anchor = parseDate(rule.startsOn) ?: continue
            val dates = Recurrence.occurrences(
                freq = rule.freq,
                anchor = anchor,
                endsOn = rule.endsOn?.let(::parseDate),
                through = today,
            )
            if (dates.isEmpty()) continue

            val ids = dates.map { Recurrence.occurrenceId(rule.id, it) }
            // Chunked because Room expands `IN (:ids)` to one bind variable per
            // id, and SQLite's limit is 999 on older Android builds.
            val known = ids.chunked(500).flatMap { dao.existingTransactionIds(it) }.toSet()

            val fresh = dates.asSequence()
                .map { it to Recurrence.occurrenceId(rule.id, it) }
                .filterNot { it.second in known }
                .take(MAX_NEW_PER_PASS)
                .toList()
            if (fresh.isEmpty()) continue

            dao.upsertTransactions(
                fresh.map { (date, id) ->
                    val at = Recurrence.occurredAt(date)
                    TransactionEntity(
                        id = id,
                        kind = rule.kind,
                        amountMinor = rule.amountMinor,
                        accountId = rule.accountId,
                        categoryId = rule.categoryId,
                        note = rule.note,
                        occurredAt = at,
                        occurredOn = date.toString(),
                        // The rule's author, not whoever's phone happened to run
                        // this: every field has to be a pure function of
                        // (rule, date) or two phones overwrite each other.
                        createdBy = rule.createdBy,
                        recurringRuleId = rule.id,
                        createdAt = at,
                        pending = 1,
                    )
                },
            )
            written += fresh.size
        }
        return written
    }

    private fun parseDate(value: String): LocalDate? =
        runCatching { LocalDate.parse(value) }.getOrNull()

    /**
     * Step 3 of the restore runbook. Without this, the copies of the data
     * sitting on four phones cannot be used to repair the server.
     */
    suspend fun reuploadEverything() {
        dao.markAllAccountsPending()
        dao.markAllCategoriesPending()
        dao.markAllBudgetsPending()
        dao.markAllMonthPlansPending()
        dao.markAllRecurringRulesPending()
        dao.markAllTransactionsPending()
    }

    companion object {
        /**
         * How many transactions one rule may create in a single pass.
         *
         * A limit on damage, not on the schedule. A rule whose anchor year was
         * mistyped, or a phone whose clock is wrong, would otherwise fill the
         * history in one go. Occurrences are taken oldest first, so a rule with
         * a genuine backlog still drains it — a pass at a time, visibly, instead
         * of in one silent flood.
         */
        internal const val MAX_NEW_PER_PASS = 60

        /**
         * On the companion so a test can pin the direction without a database.
         * Inverting this is the one mistake here that fails silently and
         * completely: every overview figure would read zero, with no error and
         * no empty state to explain it.
         */
        internal fun allAccounts(ids: Set<String>): Int = if (ids.isEmpty()) 1 else 0

        /**
         * The five fields an editor changes, folded onto a whole row.
         *
         * Here rather than in a ViewModel because three screens now edit the same
         * transaction — History, Overview and the voice summary — and three copies
         * of this would drift. The one that matters is `occurredOn`: it is derived,
         * not typed, and every month query buckets on it, so an edit that moved the
         * date and forgot to recompute it leaves the row in its old month for every
         * total in the app while showing the new date on its face.
         *
         * A whole row, not a patch, because the sync protocol carries whole rows
         * and there is no partial-update path to get wrong.
         */
        fun applyEdit(
            original: TransactionEntity,
            amountMinor: Long,
            categoryId: String?,
            accountId: String,
            note: String,
            occurredAtMs: Long,
        ): TransactionEntity = original.copy(
            amountMinor = amountMinor,
            categoryId = categoryId,
            accountId = accountId,
            note = note.ifBlank { null },
            occurredAt = occurredAtMs,
            occurredOn = Dates.localDate(occurredAtMs),
        )
    }
}
